# Generated by Django 6.0.1 on 2026-01-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=160)),
                ('job_url', models.URLField()),
                ('location_type', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=10)),
                ('referral', models.BooleanField(default=False)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_applied', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'job_url'), name='unique_job_url_per_user')],
            },
        ),
    ]
